# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['launcher.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'numpy',
        'numpy.core',
        'numpy.core._multiarray_umath',
        'pygame',
        'psutil',
        'pymem',
        'win32api',
        'win32con',
        'win32gui',
        'pywintypes',
        'requests',
        'tkinter',
        'tkinter.ttk',
        'tkinter.messagebox',
        'json',
        'threading',
        'dataclasses',
        'ctypes',
        'struct',
        'logging',
        'argparse',
        'subprocess',
        'sys',
        'os',
        'time',
        'math',
        'random',
        'enum',
        'typing',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='aimbot_gui',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
